"""production_hardening_indexes_security_fields

Revision ID: 50d559069f58
Revises: cfe00cb3c81a
Create Date: 2026-04-21 16:43:20.522592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d559069f58'
down_revision: Union[str, Sequence[str], None] = 'cfe00cb3c81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # extra_info stays TEXT — existing data has Python repr strings; migrate to JSONB in a future migration after data cleanup
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_performed_at'), 'audit_logs', ['performed_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.add_column('transactions', sa.Column('created_by_name', sa.String(), nullable=True))
    op.execute("ALTER TABLE transactions ALTER COLUMN anomaly_score TYPE NUMERIC(5,4) USING anomaly_score::numeric(5,4)")
    op.create_index('ix_transactions_account_date', 'transactions', ['account_number', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index('ix_transactions_type_date', 'transactions', ['transaction_type', 'created_at'], unique=False)
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_login_count')
    op.drop_column('users', 'last_login')
    op.drop_index('ix_transactions_type_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.alter_column('transactions', 'anomaly_score',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('transactions', 'created_by_name')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_performed_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    # extra_info stays TEXT — no downgrade needed
    # ### end Alembic commands ###
